services:
  db:
    image: postgres:16
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=purple
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  rfced:
    build:
      context: .
      dockerfile: docker/rfced.Dockerfile
    volumes:
      - rfced-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=abcd1234
      - MARIADB_DATABASE=rfced

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8888:8000"
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=abcd1234
      - MARIADB_DATABASE=rfced
      - PURPLE_DEPLOYMENT_MODE=development
      - POSTGRES_DB=purple
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RPC_API_TOKEN=devtoken
      # OIDC RP client credential for dev instance of datatracker (not secret for dev, will be for production)
      - PURPLE_OIDC_RP_CLIENT_ID=502412
      - PURPLE_OIDC_RP_CLIENT_SECRET=4046925638956f0d733cd96a5a89646815f0e989c878e9e09475b2f8
    depends_on:
      - db
      - rfced
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
        - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
        - PGADMIN_DISABLE_POSTFIX=True
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        - SCRIPT_NAME=/pgadmin
    volumes:
        - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
  rfced-data:
