# Generated by Django 5.2 on 2025-04-30 21:14

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import errata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datatracker", "0003_document_intended_std_level"),
        ("rpc", "0004_populate_capability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "slug",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField(blank=True)),
                ("used", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "slug",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField(blank=True)),
                ("used", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Errata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.TextField(blank=True)),
                ("orig_text", models.TextField(blank=True)),
                ("corrected_text", models.TextField(blank=True)),
                ("submitter_name", models.CharField(blank=True, max_length=80)),
                ("submitter_email", models.EmailField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateField()),
                ("posted_at", models.DateField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", errata.models.AutoDateTimeField()),
                (
                    "format",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("HTML", "HTML"), ("PDF", "PDF"), ("TXT", "TXT")],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        help_text="A list of formats. Possible values: 'HTML', 'PDF', and 'TXT'.",
                        size=None,
                    ),
                ),
                (
                    "rfc_to_be",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errata",
                        to="rpc.rfctobe",
                    ),
                ),
                (
                    "submitter_dt_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errata_submitter_dt_person",
                        to="datatracker.datatrackerperson",
                    ),
                ),
                (
                    "verifier_dt_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errata_verifier_dt_person",
                        to="datatracker.datatrackerperson",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default="reported",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errata",
                        to="errata.status",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errata",
                        to="errata.type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.TextField(blank=True)),
                ("orig_text", models.TextField(blank=True)),
                ("corrected_text", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "editor_dt_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_editor_dt_person",
                        to="datatracker.datatrackerperson",
                    ),
                ),
                (
                    "errata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_errata",
                        to="errata.errata",
                    ),
                ),
                (
                    "verifier_dt_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_verifier_dt_person",
                        to="datatracker.datatrackerperson",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_status",
                        to="errata.status",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_type",
                        to="errata.type",
                    ),
                ),
            ],
        ),
    ]
