name: Build DB Image

on:
  # Run early every North American morning, not near the top of an hour
  schedule:
   - cron: '23 9 * * *'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Main
    runs-on:
      group: hperf-8c32r
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: false
        path: rfced-xfer

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: false
        ref: feat/rpc-api
        repository: ietf-tools/datatracker
        path: datatracker

    - name: Docker Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      timeout-minutes: 60
      env:
        AZURE_STORAGE_ACCOUNT: ietfbackup
        AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "=========================================================================="
        echo "Fetch latest rfced DB dump..."
        echo "=========================================================================="
        echo "Querying latest dump..."
        export LATESTDBKEY=$(az storage blob list -c database --prefix rfcpa/rfced --query "[-1:].name | [0]" --out tsv)
        echo "Downloading latest DB dump ($LATESTDBKEY)..."
        az storage blob download -c database -n $LATESTDBKEY -f rfced-xfer/dump.sql.gz

        echo "=========================================================================="
        echo "Configure Datatracker..."
        echo "=========================================================================="
        sed -i "s/'HOST': 'db',/'HOST': 'datatrackerdb',/" datatracker/docker/configs/settings_postgresqldb.py

        echo "=========================================================================="
        echo "Run the project..."
        echo "=========================================================================="
        cd ${{ github.workspace }}/rfced-xfer
        echo "Building app images..."
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml build --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
        echo "Launching compose project..."
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml up -d

        echo "=========================================================================="
        echo "Run migration script..."
        echo "=========================================================================="
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml exec app bash ci-migrate.sh

        echo "=========================================================================="
        echo "Export purple PostgreSQL DB dump..."
        echo "=========================================================================="
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml exec db pg_dump -U postgres -F c --clean --no-owner --no-privileges purple > purple.dump
        ls -lh purple.dump

        echo "=========================================================================="
        echo "Add purple staging OIDC redirect url to client"
        echo "=========================================================================="
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml exec datatrackerdb psql -U django -d datatracker -c "INSERT INTO datatracker.oidc_provider_client VALUES (DEFAULT, 'Purple Staging', '173327', 'd78945c377b5ed188dfa88b0cfadea9049a5d41fe7934847fdf2a5bc', E'https://purple.staging.ietf.org/oidc/callback/', '$(date +'%Y-%m-%d')', 'confidential', 'RS256', 'tools-help@ietf.org', '', '', 'https://ietf.org', '', FALSE, FALSE, 2706, '');"
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml exec datatrackerdb psql -U django -d datatracker -c "INSERT INTO datatracker.oidc_provider_client_response_types (client_id, responsetype_id) SELECT id, 1 FROM datatracker.oidc_provider_client WHERE client_id='173327';"

        echo "=========================================================================="
        echo "Export datatracker PostgreSQL DB dump..."
        echo "=========================================================================="
        # Only exports datatracker schema. The public schema must exist and contain the required extensions.
        # The following set is sufficient (but perhaps not minimal):
        #  bloom, btree_gin, btree_gist, citext, fuzzystrmatch, pg_buffercache, pg_stat_statements, pg_trgm,
        #  pgrowlocks, pgstattuple
        sudo docker compose -f docker-compose.yml -f docker/docker-compose.datatracker.yml exec datatrackerdb pg_dump -U django -F c --clean --no-owner --no-privileges --schema=datatracker datatracker > datatracker.dump
        ls -lh datatracker.dump

        echo "=========================================================================="
        echo "Upload PostgreSQL DB dumps..."
        echo "=========================================================================="
        az storage blob upload -f purple.dump -c database -n purple/purple-$(date +"%FT%H%M").dump --tier Cool
        az storage blob upload -f datatracker.dump -c database -n purple/datatracker-$(date +"%FT%H%M").dump --tier Cool
